databases:
  - name: gamify_db
    databaseName: gamify
    user: gamify
    plan: free

services:
  - type: web
    name: gamify
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: >
      python manage.py collectstatic --no-input &&
      python manage.py migrate &&
      gunicorn gamify.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gamify_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com

  - type: worker
    name: notification-cleanup
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run_notification_cleanup.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gamify_db
          property: connectionString
      - key: DEBUG
        value: False
