# Generated by Django 5.0.2 on 2025-04-03 11:40

import messaging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=messaging.models.audio_file_path),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=messaging.models.audio_file_path),
        ),
        migrations.AlterField(
            model_name='communitymessage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
